"""Danh mục 127 phường/xã Hà Nội.

TỰ SINH — đừng sửa tay. Nguồn sự thật là
`src/frontend/src/data/hanoi_wards.js`; chạy `python scripts/sync_wards.py`
để cập nhật file này.
"""

HANOI_WARDS: tuple[str, ...] = (
    "Hoàn Kiếm",
    "Cửa Nam",
    "Ba Đình",
    "Ngọc Hà",
    "Giảng Võ",
    "Hai Bà Trưng",
    "Vĩnh Tuy",
    "Bạch Mai",
    "Đống Đa",
    "Kim Liên",
    "Văn Miếu - Quốc Tử Giám",
    "Ô Chợ Dừa",
    "Láng",
    "Hồng Hà",
    "Tây Hồ",
    "Phú Thượng",
    "Cầu Giấy",
    "Nghĩa Đô",
    "Yên Hòa",
    "Thanh Xuân",
    "Khương Đình",
    "Phương Liệt",
    "Long Biên",
    "Bồ Đề",
    "Việt Hưng",
    "Phúc Lợi",
    "Hoàng Mai",
    "Vĩnh Hưng",
    "Tương Mai",
    "Định Công",
    "Hoàng Liệt",
    "Yên Sở",
    "Lĩnh Nam",
    "Từ Liêm",
    "Xuân Đỉnh",
    "Đông Ngạc",
    "Thượng Cát",
    "Tây Tựu",
    "Phú Diễn",
    "Xuân Phương",
    "Tây Mỗ",
    "Đại Mỗ",
    "Hà Đông",
    "Dương Nội",
    "Yên Nghĩa",
    "Phú Lương",
    "Kiến Hưng",
    "Sơn Tây",
    "Tùng Thiện",
    "Đoài Phương",
    "Đông Anh",
    "Thư Lâm",
    "Phúc Thịnh",
    "Thiên Lộc",
    "Vĩnh Thanh",
    "Gia Lâm",
    "Thuận An",
    "Bát Tràng",
    "Phù Đổng",
    "Sóc Sơn",
    "Đa Phúc",
    "Nội Bài",
    "Trung Giã",
    "Phù Lỗ",
    "Tân Minh",
    "Hiền Ninh",
    "Mê Linh",
    "Yên Lãng",
    "Tiến Thắng",
    "Quang Minh",
    "Thanh Trì",
    "Đại Thanh",
    "Nam Phù",
    "Ngọc Hồi",
    "Thanh Liệt",
    "Hoài Đức",
    "Dương Hòa",
    "Sơn Đồng",
    "An Khánh",
    "Đan Phượng",
    "Ô Diên",
    "Liên Minh",
    "Phúc Thọ",
    "Hát Môn",
    "Thạch Thất",
    "Hạ Bằng",
    "Tây Phương",
    "Hòa Lạc",
    "Quốc Oai",
    "Hưng Đạo",
    "Kiều Phú",
    "Phú Cát",
    "Chương Mỹ",
    "Phú Nghĩa",
    "Xuân Mai",
    "Trần Phú",
    "Hồng Phú",
    "Quảng Bị",
    "Thanh Oai",
    "Bình Minh",
    "Tam Hưng",
    "Dân Hòa",
    "Thường Tín",
    "Thượng Phúc",
    "Chương Dương",
    "Hồng Vân",
    "Phú Xuyên",
    "Phượng Dực",
    "Chuyên Mỹ",
    "Đại Xuyên",
    "Ứng Hòa",
    "Hòa Xá",
    "Vân Đình",
    "Ứng Thiên",
    "Mỹ Đức",
    "Hồng Sơn",
    "Phúc Sơn",
    "Hương Sơn",
    "Ba Vì",
    "Vật Lại",
    "Cổ Đô",
    "Bất Bạt",
    "Minh Châu",
    "Tản Viên Sơn",
    "Yên Bài",
    "Quảng Oai",
    "Suối Hai",
)
